### ISSUE TITLE
Crear dentro de IContactoService y ContactoServiceImp la función eliminar

### ISSUE THREAD

**Issue by JavierBurgoz** [RE-M4/rep-TP-PV-UNJu#187]
Para  IcontactoService:
public void borrarMensajes(Contacto contacto);

Para ContactoServiceImp:
@Override
	public void borrarMensajes(Contacto contacto) {
		listaMensajes.getListaMensaje().remove(contacto);
	}

**Comment by RE-M4** [comment]
Terminado.
