### ISSUE TITLE
Cambiar la funcionalidad del apartado "categoría" de Producto

### ISSUE THREAD

**Issue by RE-M4** [RE-M4/rep-TP-PV-UNJu#226]
El campo categoría deberá ser una lista con opciones, por ejemplo: Alimento, Accesorios, Higiene, Vestimenta, etc.

**Comment by elias38470** [comment]
se cambio el input de categoria por un select para mostrar la lista de categorias d2fd560df7f8aa0f5d87a3be596645431e8427db
