### ISSUE TITLE
Imágenes de consejos de salud

### ISSUE THREAD

**Issue by mmarcoschambi** [RE-M4/rep-TP-PV-UNJu#90]
Las imágenes que no se muestran pueden estar corrompidas. Están bien llamadas desde el código correctamente, pero al abrir desde el archivo no se pueden visualizar. Prueba a resubir las imágenes dañadas.
![image](https://user-images.githubusercontent.com/126689946/235286914-a334945b-1bc0-4d5f-8009-32dd54d81a42.png)

**Comment by RE-M4** [comment]
Arreglado.
